### ISSUE TITLE
On first/last pages, Next or Previous don't appear but show selected state.

### ISSUE THREAD

**Issue by derekbrameyer** [ManuelPeinado/NumericPageIndicator#1]
I have a NumericPageIndicator with showStartEndButtons set to false.

On the first and last pages, while "Next" or "Previous" aren't displayed, the button where they should be still shows presses.

**Comment by ManuelPeinado** [comment]
Happens to go to first / last page buttons as well. Thanks!

**Comment by ManuelPeinado** [comment]
Fixed in 1.1.1
